// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4_CABhIEnnqcX-32DSOTDSCAvqxZpt-k',
    appId: '1:185708456928:web:4ee8514096fc8dcc191985',
    messagingSenderId: '185708456928',
    projectId: 'noise-pollution-mapper-9ad3d',
    authDomain: 'noise-pollution-mapper-9ad3d.firebaseapp.com',
    storageBucket: 'noise-pollution-mapper-9ad3d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-gBktWS-mebPrFK0M9Bxt_7Y7A2ALezI',
    appId: '1:185708456928:android:84881c81b95eafd4191985',
    messagingSenderId: '185708456928',
    projectId: 'noise-pollution-mapper-9ad3d',
    storageBucket: 'noise-pollution-mapper-9ad3d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkZNC3r0G_4cCKi95eTU42vIKME1l-MGQ',
    appId: '1:185708456928:ios:2cac42f1845a4a6c191985',
    messagingSenderId: '185708456928',
    projectId: 'noise-pollution-mapper-9ad3d',
    storageBucket: 'noise-pollution-mapper-9ad3d.firebasestorage.app',
    iosBundleId: 'com.noisemapper.noisePollutionMapper',
  );
}
